package server

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type LaunchOptions struct {
	ClusterID           string
	ClusterDir          string
	SessionName         string   // defaults to Server.Name when empty
	ServerPassword      string   // optional player password
	ServerAdminPassword string   // optional; falls back to Server.RCONPassword
	Mods                []int    // CurseForge mod IDs in load order
	ActiveEvent string
	ExtraArgs   []string
}

func ResolveActiveEvent(serverEvent, clusterEvent string) string {
	ev := serverEvent
	if ev == "" {
		ev = clusterEvent
	}
	if ev == "None" {
		return ""
	}
	return ev
}

type LaunchCommand struct {
	Exe  string
	Args []string
}

func (l LaunchCommand) Line() string {
	parts := make([]string, 0, len(l.Args)+1)
	parts = append(parts, quoteIfNeeded(l.Exe))
	parts = append(parts, l.Args...)
	return strings.Join(parts, " ")
}

// BuildLaunchCommand constructs the ArkAscendedServer command line for s using opts.
func BuildLaunchCommand(s Server, opts LaunchOptions) LaunchCommand {
	sessionName := opts.SessionName
	if sessionName == "" {
		sessionName = s.Name
	}
	adminPass := opts.ServerAdminPassword
	if adminPass == "" {
		adminPass = s.RCONPassword
	}

	chain := []string{
		s.Map,
		"listen",
		"SessionName=" + sanitizeChainValue(sessionName),
		fmt.Sprintf("Port=%d", s.Ports.Game),
		fmt.Sprintf("QueryPort=%d", s.Ports.Query),
		fmt.Sprintf("RCONPort=%d", s.Ports.RCON),
		"RCONEnabled=True",
	}
	if opts.ServerPassword != "" {
		chain = append(chain, "ServerPassword="+sanitizeChainValue(opts.ServerPassword))
	}
	if adminPass != "" {
		chain = append(chain, "ServerAdminPassword="+sanitizeChainValue(adminPass))
	}
	chainArg := strings.Join(chain, "?")

	flags := []string{
		chainArg,
		"-server",
	}
	if opts.ClusterID != "" {
		flags = append(flags, "-clusterid="+opts.ClusterID)
	}
	if opts.ClusterDir != "" {
		flags = append(flags, "-ClusterDirOverride="+quoteIfNeeded(opts.ClusterDir))
	}
	if len(opts.Mods) > 0 {
		ids := make([]string, len(opts.Mods))
		for i, m := range opts.Mods {
			ids[i] = strconv.Itoa(m)
		}
		flags = append(flags, "-mods="+strings.Join(ids, ","))
	}
	if opts.ActiveEvent != "" && opts.ActiveEvent != "None" {
		flags = append(flags, "-ActiveEvent="+opts.ActiveEvent)
	}

	if !s.AnticheatEnabled {
		flags = append(flags, "-NoBattlEye")
	}
	flags = append(flags, opts.ExtraArgs...)

	exe := filepath.Join(s.InstallDir, "ShooterGame", "Binaries", "Win64", "ArkAscendedServer.exe")
	return LaunchCommand{Exe: exe, Args: flags}
}

func WriteBatchFile(s Server, cmd LaunchCommand) (string, error) {
	if err := os.MkdirAll(s.InstallDir, 0o755); err != nil {
		return "", err
	}
	name := "start-" + sanitizeFilename(s.Name) + ".bat"
	path := filepath.Join(s.InstallDir, name)
	body := "@echo off\r\n" +
		"REM Generated by asamanager. Edits will be overwritten on next save.\r\n" +
		cmd.Line() + "\r\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func sanitizeChainValue(s string) string {
	repl := strings.NewReplacer(" ", "_", "?", "", "=", "", `"`, "")
	return repl.Replace(s)
}

func quoteIfNeeded(s string) string {
	if s == "" || !strings.ContainsAny(s, " \t") {
		return s
	}
	return `"` + s + `"`
}

func sanitizeFilename(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "server"
	}
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9',
			r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
